### ISSUE TITLE
Fix Release CD

### ISSUE THREAD

**Issue by galibey** [infinyon/fluvio-client-java#119]
Release CD successfully publishes the artifact, but setting the next version to SNAPSHOT and pushing it fails with:
```
remote: Permission to infinyon/fluvio-client-java.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/infinyon/fluvio-client-java/': The requested URL returned error: 403
```

**Comment by morenol** [comment]
Fixed with https://github.com/infinyon/fluvio-client-java/commit/4ec8cf5040755bf9964184ec6de38fc168e9a7c6
