### ISSUE TITLE
Follow Java Code Convention

### ISSUE THREAD

**Issue by galibey** [infinyon/fluvio-client-java#63]
We should follow Java Code Convention for exposed Java API. For example, no underscores in method names. Users of the client may have some warning from static code analyzers when they use Java Client API.

**Comment by simlay** [comment]
I don't suppose there's some lint CI or something we can put in here? Fixing this isn't hard. I think we just need to change things like [`partition_consumer`](https://github.com/infinyon/fluvio-client-java/blob/3a6e1c217de92adb6490b7501aced66441a7714b/src/java_glue.rs.in#L83) to `partitionConsumer` and such.

**Comment by galibey** [comment]
Checkstyle is the most commonly used tool for this. There is a plugin for Gradle https://docs.gradle.org/current/userguide/checkstyle_plugin.html. 
Snippet:
```
plugins {
    ...
    id 'checkstyle'
}
checkstyle {
  ignoreFailures = false
  maxWarnings = 0
}
...
```
The popular configuration is https://github.com/checkstyle/checkstyle/blob/checkstyle-8.37/src/main/resources/google_checks.xml (version matters, better to have same as plugin's )

**Comment by galibey** [comment]
Fixed in https://github.com/infinyon/fluvio-client-java/pull/67
